### ISSUE TITLE
Not working in Inkscape 1.3

### ISSUE THREAD

**Issue by storkweb** [buxtronix/living-hinge#10]
Hi, to use with Inkscape 1.3 you must edit the living_hinge.inx file and remove the line "<dependency type="executable" location="extensions">inkex.py</dependency>" otherwise you get an error finding inkex.py file and a greyed out useless entry in the menu.

**Comment by jbfly** [comment]
Thanks! This worked for me. I'm running 1.3.2. I'm using Arch btw. ;)

I was seeing the same issue where it was grayed out...

**Comment by storkweb** [comment]
I'm also on Arch (Manjaro)
Glad it helped


⁣Didier SZYLOWICZ - StorkWEB​

Le 28 mai 2024, 09:43, à 09:43, John Bonewitz ***@***.***> a écrit:

**Comment by buxtronix** [comment]
Fixed in newest release.
