### ISSUE TITLE
Bounding box selection incorrect

### ISSUE THREAD

**Issue by tinxx** [buxtronix/living-hinge#7]
When objects are selected the script tries to fill their bounding boxes with the pattern.

That does not work correctly in Inkscape 1.2.2.

---

Your script converts the units using `self.svg.unittouu()`.
However, that does not seem to be working as intended (anymore).

I am not knowledgeable with Inkscape extension programming but removing the conversion seems to work most of the time:

```diff
--- a/living_hinge.py
+++ b/living_hinge.py
@@ -471,11 +471,9 @@ class LivingHingeEffect(inkex.EffectExtension):
             for elem in self.svg.selected.values():
                 # Determine width and height based on the selected object's bounding box.
                 bbox = elem.bounding_box()
-                self.options.width = self.svg.unittouu(bbox.width)
-                self.options.height = self.svg.unittouu(bbox.height)
-                x = self.svg.unittouu(bbox.x.minimum)
-                y = self.svg.unittouu(bbox.y.minimum)
-                draw_one(x, y)
+                self.options.width = bbox.width
+                self.options.height = bbox.height
+                draw_one(bbox.x.minimum, bbox.y.minimum)
```

However, sometimes the pattern is drawn out of bounds. I am not sure if this is another problem due to the newer versions of Inkscape/inkex or a known problem.
See attached screenshot:

![Screenshot from 2023-04-02 14-04-40](https://user-images.githubusercontent.com/13608545/229352061-54d456eb-ed3a-4526-8e36-67f93e9b86ad.png)

**Comment by amoose136** [comment]
The overrun problem appears to be on Inkscape's side. You can hard code the value of the box in place of bbox.width and bbox.height for any shape that's overrunning and it's perfect.

**Comment by tinxx** [comment]
Hi @amoose136, thanks for the reply.

Have you been able to reproduce my problem with the `unittouu()`?

The issue that the bounding box is sometimes exceeded was more like a sidenote. I believe that my PR is still valid.
